// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gRPC_LookUpService/ServerStreaming/pb/lookup.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LookingUp struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookingUp) Reset()         { *m = LookingUp{} }
func (m *LookingUp) String() string { return proto.CompactTextString(m) }
func (*LookingUp) ProtoMessage()    {}
func (*LookingUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d4f938de6953b1c, []int{0}
}

func (m *LookingUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookingUp.Unmarshal(m, b)
}
func (m *LookingUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookingUp.Marshal(b, m, deterministic)
}
func (m *LookingUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookingUp.Merge(m, src)
}
func (m *LookingUp) XXX_Size() int {
	return xxx_messageInfo_LookingUp.Size(m)
}
func (m *LookingUp) XXX_DiscardUnknown() {
	xxx_messageInfo_LookingUp.DiscardUnknown(m)
}

var xxx_messageInfo_LookingUp proto.InternalMessageInfo

func (m *LookingUp) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *LookingUp) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type LookUpRequest struct {
	LookingUp            *LookingUp `protobuf:"bytes,1,opt,name=lookingUp,proto3" json:"lookingUp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LookUpRequest) Reset()         { *m = LookUpRequest{} }
func (m *LookUpRequest) String() string { return proto.CompactTextString(m) }
func (*LookUpRequest) ProtoMessage()    {}
func (*LookUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d4f938de6953b1c, []int{1}
}

func (m *LookUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpRequest.Unmarshal(m, b)
}
func (m *LookUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpRequest.Marshal(b, m, deterministic)
}
func (m *LookUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpRequest.Merge(m, src)
}
func (m *LookUpRequest) XXX_Size() int {
	return xxx_messageInfo_LookUpRequest.Size(m)
}
func (m *LookUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpRequest proto.InternalMessageInfo

func (m *LookUpRequest) GetLookingUp() *LookingUp {
	if m != nil {
		return m.LookingUp
	}
	return nil
}

type LookUpResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookUpResponse) Reset()         { *m = LookUpResponse{} }
func (m *LookUpResponse) String() string { return proto.CompactTextString(m) }
func (*LookUpResponse) ProtoMessage()    {}
func (*LookUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d4f938de6953b1c, []int{2}
}

func (m *LookUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpResponse.Unmarshal(m, b)
}
func (m *LookUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpResponse.Marshal(b, m, deterministic)
}
func (m *LookUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpResponse.Merge(m, src)
}
func (m *LookUpResponse) XXX_Size() int {
	return xxx_messageInfo_LookUpResponse.Size(m)
}
func (m *LookUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpResponse proto.InternalMessageInfo

func (m *LookUpResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*LookingUp)(nil), "lookup.LookingUp")
	proto.RegisterType((*LookUpRequest)(nil), "lookup.LookUpRequest")
	proto.RegisterType((*LookUpResponse)(nil), "lookup.LookUpResponse")
}

func init() {
	proto.RegisterFile("gRPC_LookUpService/ServerStreaming/pb/lookup.proto", fileDescriptor_2d4f938de6953b1c)
}

var fileDescriptor_2d4f938de6953b1c = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4a, 0x0f, 0x0a, 0x70,
	0x8e, 0xf7, 0xc9, 0xcf, 0xcf, 0x0e, 0x2d, 0x08, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x07,
	0xd1, 0xa9, 0x45, 0xc1, 0x25, 0x45, 0xa9, 0x89, 0xb9, 0x99, 0x79, 0xe9, 0xfa, 0x05, 0x49, 0xfa,
	0x39, 0xf9, 0xf9, 0xd9, 0xa5, 0x05, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e,
	0x92, 0x3b, 0x17, 0x27, 0x48, 0x63, 0x66, 0x5e, 0x7a, 0x68, 0x81, 0x90, 0x2c, 0x17, 0x57, 0x5a,
	0x66, 0x51, 0x71, 0x49, 0x7c, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x27, 0x58, 0xc4, 0x2f, 0x31, 0x37, 0x55, 0x48, 0x9a, 0x8b, 0x33, 0x27, 0x11, 0x26, 0xcb, 0x04,
	0x96, 0xe5, 0x00, 0x09, 0x80, 0x24, 0x95, 0x1c, 0xb8, 0x78, 0x21, 0x2e, 0x08, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x11, 0xd2, 0xe7, 0xe2, 0xcc, 0x81, 0x99, 0x0c, 0x36, 0x8b, 0xdb, 0x48, 0x50,
	0x0f, 0xea, 0x06, 0xb8, 0x95, 0x41, 0x08, 0x35, 0x4a, 0x1a, 0x5c, 0x7c, 0x30, 0x13, 0x8a, 0x0b,
	0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x8a, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0xc0, 0xfa,
	0x59, 0x83, 0xa0, 0x3c, 0xa3, 0x69, 0x8c, 0x30, 0xcb, 0xa0, 0xde, 0x15, 0xb2, 0xe4, 0x62, 0x83,
	0x08, 0x08, 0x89, 0x22, 0xdb, 0x01, 0x77, 0x8d, 0x94, 0x18, 0xba, 0x30, 0xc4, 0x0a, 0x25, 0x06,
	0x21, 0x2f, 0x2e, 0x51, 0x84, 0x59, 0x48, 0x41, 0x46, 0xb2, 0x49, 0x06, 0x8c, 0x4e, 0x2c, 0x51,
	0x4c, 0x05, 0x49, 0x49, 0x6c, 0xe0, 0x20, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xe7,
	0xd8, 0x71, 0x98, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LookUpServiceClient is the client API for LookUpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LookUpServiceClient interface {
	//unary
	LookUp(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (*LookUpResponse, error)
	//ServerStreaming
	LookUpServerStreaming(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (LookUpService_LookUpServerStreamingClient, error)
}

type lookUpServiceClient struct {
	cc *grpc.ClientConn
}

func NewLookUpServiceClient(cc *grpc.ClientConn) LookUpServiceClient {
	return &lookUpServiceClient{cc}
}

func (c *lookUpServiceClient) LookUp(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (*LookUpResponse, error) {
	out := new(LookUpResponse)
	err := c.cc.Invoke(ctx, "/lookup.LookUpService/LookUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookUpServiceClient) LookUpServerStreaming(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (LookUpService_LookUpServerStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LookUpService_serviceDesc.Streams[0], "/lookup.LookUpService/LookUpServerStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &lookUpServiceLookUpServerStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LookUpService_LookUpServerStreamingClient interface {
	Recv() (*LookUpResponse, error)
	grpc.ClientStream
}

type lookUpServiceLookUpServerStreamingClient struct {
	grpc.ClientStream
}

func (x *lookUpServiceLookUpServerStreamingClient) Recv() (*LookUpResponse, error) {
	m := new(LookUpResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LookUpServiceServer is the server API for LookUpService service.
type LookUpServiceServer interface {
	//unary
	LookUp(context.Context, *LookUpRequest) (*LookUpResponse, error)
	//ServerStreaming
	LookUpServerStreaming(*LookUpRequest, LookUpService_LookUpServerStreamingServer) error
}

func RegisterLookUpServiceServer(s *grpc.Server, srv LookUpServiceServer) {
	s.RegisterService(&_LookUpService_serviceDesc, srv)
}

func _LookUpService_LookUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookUpServiceServer).LookUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lookup.LookUpService/LookUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookUpServiceServer).LookUp(ctx, req.(*LookUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookUpService_LookUpServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LookUpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LookUpServiceServer).LookUpServerStreaming(m, &lookUpServiceLookUpServerStreamingServer{stream})
}

type LookUpService_LookUpServerStreamingServer interface {
	Send(*LookUpResponse) error
	grpc.ServerStream
}

type lookUpServiceLookUpServerStreamingServer struct {
	grpc.ServerStream
}

func (x *lookUpServiceLookUpServerStreamingServer) Send(m *LookUpResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _LookUpService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lookup.LookUpService",
	HandlerType: (*LookUpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookUp",
			Handler:    _LookUpService_LookUp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LookUpServerStreaming",
			Handler:       _LookUpService_LookUpServerStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gRPC_LookUpService/ServerStreaming/pb/lookup.proto",
}
