// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Lookupservice/Unary/pb/lookup.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LookingUp struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookingUp) Reset()         { *m = LookingUp{} }
func (m *LookingUp) String() string { return proto.CompactTextString(m) }
func (*LookingUp) ProtoMessage()    {}
func (*LookingUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e025808a77f46e2f, []int{0}
}

func (m *LookingUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookingUp.Unmarshal(m, b)
}
func (m *LookingUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookingUp.Marshal(b, m, deterministic)
}
func (m *LookingUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookingUp.Merge(m, src)
}
func (m *LookingUp) XXX_Size() int {
	return xxx_messageInfo_LookingUp.Size(m)
}
func (m *LookingUp) XXX_DiscardUnknown() {
	xxx_messageInfo_LookingUp.DiscardUnknown(m)
}

var xxx_messageInfo_LookingUp proto.InternalMessageInfo

func (m *LookingUp) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *LookingUp) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type LookUpRequest struct {
	LookingUp            *LookingUp `protobuf:"bytes,1,opt,name=lookingUp,proto3" json:"lookingUp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LookUpRequest) Reset()         { *m = LookUpRequest{} }
func (m *LookUpRequest) String() string { return proto.CompactTextString(m) }
func (*LookUpRequest) ProtoMessage()    {}
func (*LookUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e025808a77f46e2f, []int{1}
}

func (m *LookUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpRequest.Unmarshal(m, b)
}
func (m *LookUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpRequest.Marshal(b, m, deterministic)
}
func (m *LookUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpRequest.Merge(m, src)
}
func (m *LookUpRequest) XXX_Size() int {
	return xxx_messageInfo_LookUpRequest.Size(m)
}
func (m *LookUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpRequest proto.InternalMessageInfo

func (m *LookUpRequest) GetLookingUp() *LookingUp {
	if m != nil {
		return m.LookingUp
	}
	return nil
}

type LookUpResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookUpResponse) Reset()         { *m = LookUpResponse{} }
func (m *LookUpResponse) String() string { return proto.CompactTextString(m) }
func (*LookUpResponse) ProtoMessage()    {}
func (*LookUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e025808a77f46e2f, []int{2}
}

func (m *LookUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpResponse.Unmarshal(m, b)
}
func (m *LookUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpResponse.Marshal(b, m, deterministic)
}
func (m *LookUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpResponse.Merge(m, src)
}
func (m *LookUpResponse) XXX_Size() int {
	return xxx_messageInfo_LookUpResponse.Size(m)
}
func (m *LookUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpResponse proto.InternalMessageInfo

func (m *LookUpResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*LookingUp)(nil), "lookup.LookingUp")
	proto.RegisterType((*LookUpRequest)(nil), "lookup.LookUpRequest")
	proto.RegisterType((*LookUpResponse)(nil), "lookup.LookUpResponse")
}

func init() {
	proto.RegisterFile("Lookupservice/Unary/pb/lookup.proto", fileDescriptor_e025808a77f46e2f)
}

var fileDescriptor_e025808a77f46e2f = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xf6, 0xc9, 0xcf, 0xcf,
	0x2e, 0x2d, 0x28, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x0f, 0xcd, 0x4b, 0x2c, 0xaa, 0xd4,
	0x2f, 0x48, 0xd2, 0xcf, 0x01, 0x0b, 0xeb, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0xb1, 0x41, 0x78,
	0x4a, 0xee, 0x5c, 0x9c, 0x20, 0xe5, 0x99, 0x79, 0xe9, 0xa1, 0x05, 0x42, 0xb2, 0x5c, 0x5c, 0x69,
	0x99, 0x45, 0xc5, 0x25, 0xf1, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0x9c, 0x60, 0x11, 0xbf, 0xc4, 0xdc, 0x54, 0x21, 0x69, 0x2e, 0xce, 0x9c, 0x44, 0x98, 0x2c, 0x13,
	0x58, 0x96, 0x03, 0x24, 0x00, 0x92, 0x54, 0x72, 0xe0, 0xe2, 0x05, 0x19, 0x14, 0x5a, 0x10, 0x94,
	0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0xa4, 0xcf, 0xc5, 0x99, 0x03, 0x33, 0x19, 0x6c, 0x16, 0xb7,
	0x91, 0xa0, 0x1e, 0xd4, 0x0d, 0x70, 0x2b, 0x83, 0x10, 0x6a, 0x94, 0x34, 0xb8, 0xf8, 0x60, 0x26,
	0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0x15, 0xa5, 0x16, 0x97, 0xe6, 0x94,
	0x80, 0xf5, 0xb3, 0x06, 0x41, 0x79, 0x46, 0x5e, 0x30, 0xbb, 0x82, 0x21, 0x7e, 0x14, 0xb2, 0xe4,
	0x62, 0x83, 0x08, 0x08, 0x89, 0x22, 0x5b, 0x01, 0x77, 0x8c, 0x94, 0x18, 0xba, 0x30, 0xc4, 0x06,
	0x25, 0x06, 0x27, 0x96, 0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0x70, 0xa8, 0x18, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x33, 0xe7, 0xf7, 0x62, 0x3c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LookUpServiceClient is the client API for LookUpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LookUpServiceClient interface {
	//unary
	LookUp(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (*LookUpResponse, error)
}

type lookUpServiceClient struct {
	cc *grpc.ClientConn
}

func NewLookUpServiceClient(cc *grpc.ClientConn) LookUpServiceClient {
	return &lookUpServiceClient{cc}
}

func (c *lookUpServiceClient) LookUp(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (*LookUpResponse, error) {
	out := new(LookUpResponse)
	err := c.cc.Invoke(ctx, "/lookup.LookUpService/LookUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LookUpServiceServer is the server API for LookUpService service.
type LookUpServiceServer interface {
	//unary
	LookUp(context.Context, *LookUpRequest) (*LookUpResponse, error)
}

func RegisterLookUpServiceServer(s *grpc.Server, srv LookUpServiceServer) {
	s.RegisterService(&_LookUpService_serviceDesc, srv)
}

func _LookUpService_LookUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookUpServiceServer).LookUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lookup.LookUpService/LookUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookUpServiceServer).LookUp(ctx, req.(*LookUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LookUpService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lookup.LookUpService",
	HandlerType: (*LookUpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookUp",
			Handler:    _LookUpService_LookUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Lookupservice/Unary/pb/lookup.proto",
}
